sgt_ucbc/accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('profile/', views.user_profile, name='profile'),
    path('create/', views.create_account, name='create'),
    path('profile/change/', views.change_profile, name='change-profile'),

]

sgt_ucbc/sgt/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from sgt import views as sgt_views

#app_name = 'sgt'

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    # Home Page: Shows a list of recent articles
    path('', sgt_views.home, name='home'),

    #about
    path('about/', sgt_views.about, name='about'),
    
    #memoire detail
    path('memoire/<int:memoire_id>/', sgt_views.memoire_detail, name='memoire_detail'),
    path('memoire/ajouter/', sgt_views.ajouter_memoire, name='ajouter_memoire'),

    #proposition de sujet recommandation et recherche de similaires mémoires
    path('compare/', sgt_views.compare, name='proposer_memoire'),

    #depot de sujet mémoires
    path('sujet/<int:sujet_id>/', sgt_views.sujet_proposer, name='sujet_proposer'),
    path('sujet/deposer_sujet/', sgt_views.deposer_sujet, name='deposer_sujet'),
    

    path('recherche/', sgt_views.rechercher_memoire, name='rechercher_memoire'),


    path('dashboard/', sgt_views.dashboard_etudiant, name='dashboard_etudiant'),
    
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sgt_ucbc/sgt_ucbc/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sgt.urls')),    
]

sgt_ucbc/base/models.py
from django.db import models

# Create your models here.

sgt_ucbc/base/views.py
from django.shortcuts import render

# Create your views here.

sgt_ucbc/base/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title%} {% endblock %}</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/14273d579a.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>

<body class="container-fluid">
    {% include 'header.html' %}
    {% block content %}

    {% endblock %}
    <footer class="row bg-dark text-white text-center mt-3">
        <p>Designed by CEDRIC MUTEYA L3 FTSI Génie Info UCBC</p>
        <p>&copy; 2024 Université Chrétienne Bilingue du Congo. Tous droits réservés.</p>
    </footer>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="{%static 'js/bootstrap.bundle.min.js'%}"></script>
</body>

</html>

sgt_ucbc/base/templates/header.html
{%block content%}
{% load static%}
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-between py-3 mb-4 border-bottom">
        <div class="col-12 col-md-3 mb-2 mb-md-0 text-center text-md-start">
            <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
                <img src="{%static 'img/sgt_ucbc_logo.png'%}" class="img-fluid" width="200px" alt="Logo UCBC SGT">
            </a>
        </div>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li>
                <h5><a href="{%url 'home'%}" class="nav-link px-2 link-secondary">Accueil</a></h5>
            </li>
            <li>
                <h5><a href="{%url 'home'%}" class="nav-link px-2">Travaux</a></h5>
            </li>
            <li>
                <h5><a href="{%url 'about'%}" class="nav-link px-2">A propos</a></h5>
            </li>
        </ul>

        <form action="{% url 'rechercher_memoire' %}"
            class="d-flex col-12 col-md-auto justify-content-center mb-2 mb-md-0" role="search">
            <input name="q" class="form-control me-2" type="search" placeholder="Trouver un mémoire"
                aria-label="Search">
            <button class="btn btn-outline-primary" type="submit">Rechercher</button>
        </form>
        {% if user.is_authenticated %}
        <a href="{%url 'accounts:profile'%}" class="text-white">
            <h5 class="bg-danger text-white p-2"><strong><i class="bi bi-person-circle"></i> {{user.username}}</strong>
        </a>
        </h5>
        {% else %}
        <div class="col-12 col-md-3 text-center text-md-end">
            <a type="button" href="{%url 'login'%}" class="btn btn-success p-2 m-2">Se connecter</a>
        </div>
        {%endif %}
    </header>
</div>
<div class="row bg-dark">.</div>
{%endblock%}